### PR TITLE
[easy] update bindings.

### PR DESCRIPTION
**Pull request by ttung**

### CODE REVIEW

**Comment by ttung** [comment]
This test failure is expected as the field rename is happening in #58

**Comment by sampierson** [comment]
Interestingly if I do `make bindings` I get 11 files changed, not 3.  Any idea why?

**Comment by ttung** [comment]
> Interestingly if I do make bindings I get 11 files changed, not 3. Any idea why?

I chopped those out of the changeset.  Let's discuss on slack.

**Comment by ttung** [comment]
Landing these changes for now.

**Pull request merged**
